### ISSUE TITLE
Identifier "admin" is not defined.

### ISSUE THREAD

**Issue by rvreugde** [david-szabo97/grav-plugin-admin-addon-user-manager#41] opened 2018-04-09 09:16 UTC
Hello,

I just updated the Admin Addon User Manager plugin te version 2.1.4, but when I want to access my pages I get an error: "Identifier "admin" is not defined."!

More info
```
/var
/www
/ictdocs.ap.be
/vendor
/pimple
/pimple
/src
/Pimple
/Container.php

                throw new FrozenServiceException($id);
            }
     
            $this->values[$id] = $value;
            $this->keys[$id] = true;
        }
     
        /**
         * Gets a parameter or an object.
         *
         * @param string $id The unique identifier for the parameter or object
         *
         * @return mixed The value of the parameter or an object
         *
         * @throws UnknownIdentifierException If the identifier is not defined
         */
        public function offsetGet($id)
        {
            if (!isset($this->keys[$id])) {
                throw new UnknownIdentifierException($id);
            }
     
            if (
                isset($this->raw[$id])
                || !\is_object($this->values[$id])
                || isset($this->protected[$this->values[$id]])
                || !\method_exists($this->values[$id], '__invoke')
            ) {
                return $this->values[$id];
            }
     
            if (isset($this->factories[$this->values[$id]])) {
                return $this->values[$id]($this);
            }
     
            $raw = $this->values[$id];
            $val = $this->values[$id] = $raw($this);
            $this->raw[$id] = $raw;
     
            $this->frozen[$id] = true;

Arguments

    "Identifier "admin" is not defined."
```

Some extra info:
```
grav-tabs-state | "{"tab-content.options.advanced":"data.content"}"
-- | --
_ga | "GA1.2.1490981046.1520345325"
grav-site-5329479 | "l7qqhig26jhj70ci56tgplphk5"
grav-site-5329479-admin | "5uvcvdrchrhcf3qn3duh06gf71"
```

**Comment by david-szabo97** [comment] 2018-04-09 10:53
Duplicate of #40 
Already fixed in 2.1.5

**Comment by rvreugde** [comment] 2018-04-09 11:15
When I install or update the plugin, I still get version 2.1.4...

```
GPM Releases Configuration: Stable



Preparing to install Admin Addon User Manager [v2.1.4]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok                             
  '- Success!  
```

**Comment by david-szabo97** [comment] 2018-04-09 22:10
![image](https://user-images.githubusercontent.com/2256104/38525699-93554e04-3c53-11e8-8798-0b53eff54a6d.png)

You can always download it from Github and install it manually. Also, it takes some time to get it updated in Grav repo.

**Closed as completed** 2018-05-18 09:29 UTC
Labels: duplicate
